### ISSUE TITLE
Getting a test running

### ISSUE THREAD

**Issue by cmcc** [rhasson/node-libpst#1]
Roy. Not sure if this is the right forum to ask this (no e-mail against your profile), but cloned node-libpst to windows machine, edited the path to the outlook.pst file and tried running ffi_nodepst.js. I see that it should print some messages to the console if it functions correctly. Using version 0.8.8 of node. Perhaps you point me to any blog posts that might describe how to use this. I'm hoping to convert a pst file over to mongodb and wanted to use node.js as a test case. Thanks. Colum

**Comment by rhasson** [comment]
I suggest not using this module since it's incomplete.  It won't work, especially not on Windows.  I haven't had the time to work on it in a long while and it needs a ton of work.

Sorry.
Roy
